### ISSUE TITLE
Sweep: Fix broken link: https://docs.sweep.dev/examples to https://docs.sweep.dev/about/examples

### ISSUE THREAD

**Issue by wmaiouiru** [sweepai/landing-page#378]
Files:
src/components/Features.tsx
src/components/Examples.tsx

Fix broken link: https://docs.sweep.dev/examples to https://docs.sweep.dev/about/examples

<details>
<summary>Checklist</summary>

- [X] `src/components/Features.tsx`
> • Locate the line of code where the URL "https://docs.sweep.dev/examples" is being used.
> • Replace the URL "https://docs.sweep.dev/examples" with the correct URL "https://docs.sweep.dev/about/examples".

- [X] `src/components/Examples.tsx`
> • Locate the line of code where the URL "https://docs.sweep.dev/examples" is being used.
> • Replace the URL "https://docs.sweep.dev/examples" with the correct URL "https://docs.sweep.dev/about/examples".

</details>

**Comment by wmaiouiru** [comment]
Instead of hard coding the url, I wonder if there is a better way to make it less error prone...

**Comment by kevinlu1248** [comment]
@wmaiouiru Unfortunately not really, since the docs are on another repo. Thanks for reporting this issue here!
